---
- name: Get key
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927 state=present

- name: Add repository and reload local package
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' update_cache=yes

- name: Update
  apt: update_cache=yes

- name: Install Mongo
  apt: name=mongodb-org state=latest update_cache=yes
