---

- include: installDebian.yml
  when: ansible_os_family == 'Debian'
  
- include: installRedHat.yml
  when: ansible_os_family == 'RedHat'
  
- name: Restart service mongod 
  service: name=mongod state=restarted  
